#! /bin/bash
#SBATCH --account=project_2009905
#SBATCH --job-name=heat-equation
#SBATCH --time=0:05:00
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=128
#SBATCH --partition=test
##SBATCH --reservation=scc-cpu

srun heat_mpi
